### ISSUE TITLE
Breaks when multiple versions left behind

### ISSUE THREAD

**Issue by JustinAiken** [bgandon/brew-cask-outdated#4]
Versions that used to be installed show up in the `brew cask info`, so the script parses the output wrong.

For example, I've previously had kitematic `0.13.0` installed, but after installing `0.13.1`, this script still thinks I'm on 0.13.0:

```shell
$ brew cask info kitematic
kitematic: 0.13.1
https://kitematic.com/
/usr/local/Caskroom/kitematic/0.13.0 (68B)
/usr/local/Caskroom/kitematic/0.13.1 (68B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/kitematic.rb
==> Name
Kitematic
==> Artifacts
Kitematic (Beta).app (app)

$ brew-cask-outdated | grep kitematic
kitematic (0.13.0 < 0.13.1)

$ cat /Applications/Kitematic\ \(Beta\).app/Contents/Info.plist | grep CFBundleVersion -A1
    <key>CFBundleVersion</key>
    <string>0.13.1</string>
```

This happens for many, not just kitematic..

**Comment by bgandon** [comment]
Hello,

That's cool you're using `brew-cask-outdated` too :)

You'll find below the steps I follow to reproduce the issue, unfortunately, I don't get the same result as you.
```
$ cd /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks

$ git log kitematic.rb |  head -n 12

$ git checkout 15d2f92968a688e48edaa375cb53b36655ce1312

$ brew cask install kitematic
==> Downloading https://github.com/docker/kitematic/releases/download/v0.13.0/Kitematic-0.13.0-Mac.zip
######################################################################## 100,0%
==> Verifying checksum for Cask kitematic
==> Moving App 'Kitematic (Beta).app' to '/Applications/Kitematic (Beta).app'
🍺  kitematic was successfully installed!

$ git checkout master

$ brew cask reinstall kitematic
==> Downloading https://github.com/docker/kitematic/releases/download/v0.13.1/Kitematic-0.13.1-Mac.zip
Already downloaded: /Users/benjamin/Library/Caches/Homebrew/Cask/kitematic--0.13.1.zip
==> Verifying checksum for Cask kitematic
==> Removing App: '/Applications/Kitematic (Beta).app'
==> Moving App 'Kitematic (Beta).app' to '/Applications/Kitematic (Beta).app'
🍺  kitematic was successfully installed!

$ brew-cask-outdated | grep kitematic
(doesn't show up anything)
```

Which leads to several questions:
1. What is the output of `brew cask info kitematic` in your case?
2. What does `brew info cask` shows at the first line? (mine is `cask: stable 0.8.1, HEAD`)
3. Did you update `kitematic` as I do above with `brew cask reinstall`, or using another way? (please describe)
4. Can you confirm you're using the latest version of `brew-cask-outdated`? (though it seems that you are)

Cheers

**Comment by JustinAiken** [comment]
> 1. What is the output of `brew cask info kitematic` in your case?

Ah, in that case it's as expected:

```shell
kitematic: 0.13.1
https://kitematic.com/
/usr/local/Caskroom/kitematic/0.13.1 (68B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/kitematic.rb
```

> 2. What does `brew info cask` shows at the first line? 

Same: `cask: stable 0.8.1, HEAD`

> 3. Did you update kitematic as I do above with `brew cask reinstall`, or using another way?

Nope, I'd been doing `brew cask install --force` - that's the breaker!

> 4. Can you confirm you're using the latest version of `brew-cask-outdated`? 

Yep, just installed it yesterday

**Comment by bgandon** [comment]
Thanks a lot for the feedback.

I just added support for `brew cask install --force`, now managing to get correct display in such case:
```
$ brew-cask-outdated | grep kitematic
kitematic (0.12.0, 0.13.0) < 0.13.1
```
Just as `brew outdated` would output!

Cheers

**Comment by JustinAiken** [comment]
Thanks! Works perfect now :)
